apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    role: demo1
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
      volumeMounts:
      - mountPath: /redis-master
        name: config
  volumes:
    - name: config
      configMap:
        name: example-redis-config
        items:
        - key: redis-config
          path: redis.conf