apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: identity-aks-kv
spec:
  type: 0
  resourceID: /subscriptions/eed27f33-cd8b-4dda-a7fb-4616d20c3ac9/resourcegroups/dev/providers/Microsoft.ManagedIdentity/userAssignedIdentities/identity-aks-kv
  clientID: 8bdfa443-4845-4212-9e2f-b68e4024387c
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: identity-aks-kv-binding
spec:
  azureIdentity: identity-aks-kv
  selector: azure-kv
